<?php
function filteration($data){
    $data=trim($data);  //removes the white spaces from before and after...
    $data=htmlspecialchars($data); // converts special chars into html entities...
    $data= strip_tags($data);//removes html and php tags...
    $data=stripslashes($data);//remove backlashes form the data...
  return $data;
}
